#ifndef GFR_FRAMEWORK_MANAGERS_INPUTMGR_INPUTKEYNUMS_H
#define GFR_FRAMEWORK_MANAGERS_INPUTMGR_INPUTKEYNUMS_H
#include "Common.h"

/*		ALLEGRO KEY CODES		*/
#define KEY_A				ALLEGRO_KEY_A;
#define KEY_B				ALLEGRO_KEY_B;
#define KEY_C				ALLEGRO_KEY_C;
#define KEY_D				ALLEGRO_KEY_D;
#define KEY_E				ALLEGRO_KEY_E;
#define KEY_F				ALLEGRO_KEY_F;
#define KEY_G				ALLEGRO_KEY_G;
#define KEY_H				ALLEGRO_KEY_H;
#define KEY_I				ALLEGRO_KEY_I;
#define KEY_J				ALLEGRO_KEY_J;
#define KEY_K				ALLEGRO_KEY_K;
#define KEY_L				ALLEGRO_KEY_L;
#define KEY_M				ALLEGRO_KEY_M;
#define KEY_N				ALLEGRO_KEY_N;
#define KEY_O				ALLEGRO_KEY_O;
#define KEY_P				ALLEGRO_KEY_P;
#define KEY_Q				ALLEGRO_KEY_Q;
#define KEY_R				ALLEGRO_KEY_R;
#define KEY_S				ALLEGRO_KEY_S;
#define KEY_T				ALLEGRO_KEY_T;
#define KEY_U				ALLEGRO_KEY_U;
#define KEY_V				ALLEGRO_KEY_V;
#define KEY_W				ALLEGRO_KEY_W;
#define KEY_X				ALLEGRO_KEY_X;
#define KEY_Y				ALLEGRO_KEY_Y;
#define KEY_Z				ALLEGRO_KEY_Z;

#define KEY_0				ALLEGRO_KEY_0;
#define KEY_1				ALLEGRO_KEY_1;
#define KEY_2				ALLEGRO_KEY_2;
#define KEY_3				ALLEGRO_KEY_3;
#define KEY_4				ALLEGRO_KEY_4;
#define KEY_5				ALLEGRO_KEY_5;
#define KEY_6				ALLEGRO_KEY_6;
#define KEY_7				ALLEGRO_KEY_7;
#define KEY_8				ALLEGRO_KEY_8;
#define KEY_9				ALLEGRO_KEY_9;

#define KEY_PAD_0			ALLEGRO_KEY_PAD_0;
#define KEY_PAD_1			ALLEGRO_KEY_PAD_1;
#define KEY_PAD_2			ALLEGRO_KEY_PAD_2;
#define KEY_PAD_3			ALLEGRO_KEY_PAD_3;
#define KEY_PAD_4			ALLEGRO_KEY_PAD_4;
#define KEY_PAD_5			ALLEGRO_KEY_PAD_5;
#define KEY_PAD_6			ALLEGRO_KEY_PAD_6;
#define KEY_PAD_7			ALLEGRO_KEY_PAD_7;
#define KEY_PAD_8			ALLEGRO_KEY_PAD_8;
#define KEY_PAD_9			ALLEGRO_KEY_PAD_9;

#define KEY_F1				ALLEGRO_KEY_F1;
#define KEY_F2				ALLEGRO_KEY_F2;
#define KEY_F3				ALLEGRO_KEY_F3;
#define KEY_F4				ALLEGRO_KEY_F4;
#define KEY_F5				ALLEGRO_KEY_F5;
#define KEY_F6				ALLEGRO_KEY_F6;
#define KEY_F7				ALLEGRO_KEY_F7;
#define KEY_F8				ALLEGRO_KEY_F8;
#define KEY_F9				ALLEGRO_KEY_F9;
#define KEY_F10				ALLEGRO_KEY_F10;
#define KEY_F11				ALLEGRO_KEY_F11;
#define KEY_F12				ALLEGRO_KEY_F12;

#define KEY_ESC				ALLEGRO_KEY_ESCAPE
#define KEY_TILDE			ALLEGRO_KEY_TILDE
#define KEY_MINUS			ALLEGRO_KEY_MINUS
#define KEY_EQUALS			ALLEGRO_KEY_EQUALS
#define KEY_BKSP			ALLEGRO_KEY_BACKSPACE
#define KEY_TAB				ALLEGRO_KEY_TAB
#define KEY_OPENBRACE		ALLEGRO_KEY_OPENBRACE
#define KEY_CLOSEBRACE		ALLEGRO_KEY_CLOSEBRACE
#define KEY_ENTER			ALLEGRO_KEY_ENTER
#define KEY_SEMICOLON		ALLEGRO_KEY_SEMICOLON
#define KEY_SEMICOLON2		ALLEGRO_KEY_SEMICOLON2
#define KEY_QUOTE			ALLEGRO_KEY_QUOTE
#define KEY_BKSLASH			ALLEGRO_KEY_BACKSLASH
#define KEY_BKSLASH2		ALLEGRO_KEY_BACKSLASH2
#define KEY_COMMA			ALLEGRO_KEY_COMMA
#define KEY_FULLSTOP		ALLEGRO_KEY_FULLSTOP
#define KEY_SLASH			ALLEGRO_KEY_SLASH
#define KEY_SPACE			ALLEGRO_KEY_SPACE
#define KEY_INSERT			ALLEGRO_KEY_INSERT
#define KEY_DEL				ALLEGRO_KEY_DELETE
#define KEY_HOME			ALLEGRO_KEY_HOME
#define KEY_END				ALLEGRO_KEY_END
#define KEY_PGUP			ALLEGRO_KEY_PGUP
#define KEY_PGDN			ALLEGRO_KEY_PGDN
#define KEY_LEFT			ALLEGRO_KEY_LEFT
#define KEY_RIGHT			ALLEGRO_KEY_RIGHT
#define KEY_UP				ALLEGRO_KEY_UP
#define KEY_DOWN			ALLEGRO_KEY_DOWN
#define KEY_PAD_SLASH		ALLEGRO_KEY_PAD_SLASH
#define KEY_PAD_ASTERISK	ALLEGRO_KEY_PAD_ASTERISK
#define KEY_PAD_MINUS		ALLEGRO_KEY_PAD_MINUS
#define KEY_PAD_PLUS		ALLEGRO_KEY_PAD_PLUS
#define KEY_PAD_DELETE		ALLEGRO_KEY_PAD_DELETE
#define KEY_PAD_ENTER		ALLEGRO_KEY_PAD_ENTER
#define KEY_PRTSCN			ALLEGRO_KEY_PRINTSCREEN
#define KEY_PAUSE			ALLEGRO_KEY_PAUSE
#define KEY_ABNT_C1			ALLEGRO_KEY_ABNT_C1
#define KEY_YEN				ALLEGRO_KEY_YEN
#define ALLEGRO_KEY_KANA	ALLEGRO_KEY_KANA
#define KEY_CONVERT			ALLEGRO_KEY_CONVERT
#define KEY_NOCONVERT		ALLEGRO_KEY_NOCONVERT
#define KEY_AT				ALLEGRO_KEY_AT
#define KEY_CIRCUMFLEX		ALLEGRO_KEY_CIRCUMFLEX
#define KEY_COLON2			ALLEGRO_KEY_COLON2
#define KEY_KANJI			ALLEGRO_KEY_KANJI
#define KEY_LSHIFT			ALLEGRO_KEY_LSHIFT
#define KEY_RSHIFT			ALLEGRO_KEY_RSHIFT
#define KEY_LCTRL			ALLEGRO_KEY_LCTRL
#define KEY_RCTRL			ALLEGRO_KEY_RCTRL
#define KEY_ALT				ALLEGRO_KEY_ALT
#define KEY_ALTGR			ALLEGRO_KEY_ALTGR
#define KEY_LWIN			ALLEGRO_KEY_LWIN
#define KEY_RWIN			ALLEGRO_KEY_RWIN
#define KEY_MENU			ALLEGRO_KEY_MENU
#define KEY_SCRLK			ALLEGRO_KEY_SCROLLLOCK
#define KEY_NUMLOCK			ALLEGRO_KEY_NUMLOCK
#define KEY_CAPSLOCK		ALLEGRO_KEY_CAPSLOCK
#define KEY_PAD_EQUALS		ALLEGRO_KEY_PAD_EQUALS
#define KEY_BKQUOTE			ALLEGRO_KEY_BACKQUOTE
#define KEY_CMD				ALLEGRO_KEY_COMMAND

// Used for array size (total # of keys)
#define KEY_MAX				ALLEGRO_KEY_MAX

/*		ALLEGRO KEY MODIFIER FLAGS		*/
#define KEYMOD_SHIFT		ALLEGRO_KEYMOD_SHIFT
#define KEYMOD_CTRL			ALLEGRO_KEYMOD_CTRL
#define KEYMOD_ALT			ALLEGRO_KEYMOD_ALT
#define KEYMOD_LWIN			ALLEGRO_KEYMOD_LWIN
#define KEYMOD_RWIN			ALLEGRO_KEYMOD_RWIN
#define KEYMOD_MENU			ALLEGRO_KEYMOD_MENU
#define KEYMOD_ALTGR		ALLEGRO_KEYMOD_ALTGR
#define KEYMOD_CMD			ALLEGRO_KEYMOD_COMMAND
#define KEYMOD_SCRLK		ALLEGRO_KEYMOD_SCROLLLOCK
#define KEYMOD_NUMLOCK		ALLEGRO_KEYMOD_NUMLOCK
#define KEYMOD_CAPSLOCK		ALLEGRO_KEYMOD_CAPSLOCK
#define KEYMOD_INALTSEQ		ALLEGRO_KEYMOD_INALTSEQ
#define KEYMOD_ACCENT1		ALLEGRO_KEYMOD_ACCENT1
#define KEYMOD_ACCENT2		ALLEGRO_KEYMOD_ACCENT2
#define KEYMOD_ACCENT3		ALLEGRO_KEYMOD_ACCENT3
#define KEYMOD_ACCENT4		ALLEGRO_KEYMOD_ACCENT4

#endif