#ifndef GFR_FRAMEWORK_NETWORKING_NETWORKENUMS_H
#define GFR_FRAMEWORK_NETWORKING_NETWORKENUMS_H

namespace networking
{
	enum NetworkStatus
	{
		CONNECTING,
		CONNECTED,
		CONNECT_FAILURE,
		DISCONNECTED,
		IDLE,
		LISTENING,
		SHUTDOWN
	};

	enum PacketTypes : unsigned char
	{
		CHARACTER_SELECT,
		CLIENT_CONNECT,
		CONNECT_RESPONSE,
		START_GAME
	};
};

#endif